# Used plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Change prefix from 'Ctrl+B' to 'Ctrl+Space'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

set-option -sg escape-time 10
set-option -g focus-events on
set -g repeat-time 0

# Should be on the bottom
run '/usr/share/tmux-plugin-manager/tpm'
